// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

/*
 * IoT Sensor Telemetry Protocol
 * Copyright(C) 2026 Matthew Gream (https://libiotdata.org)
 *
 * simulator_lora_esp32 - multi-sensor simulator on esp32
 *
 * Simulates multiple sensors (a per-board palette of the variant suite, MAC-seeded so a fleet spreads the suite out) and transmits
 * iotdata-encoded packets via the E22 LoRa radio module at randomised intervals.
 *
 * No real sensors — all readings are generated by iotdata_variant_simulator.
 */

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
#pragma GCC diagnostic ignored "-Wnested-externs"
#pragma GCC diagnostic ignored "-Wredundant-decls"

#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#pragma GCC diagnostic pop

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

#include "iotdata_config.h"
#include "iotdata_hardware.h"

// -----------------------------------------------------------------------------------------------------------------------------------------
// CONFIGURABLES
// -----------------------------------------------------------------------------------------------------------------------------------------

#define POLL_INTERVAL_MS   100 /* simulator poll granularity */
#define STATUS_EVERY_N_TX  50  /* print status every N transmissions */
#define TRANSMIT_DELAY_MS  5
#define CONSOLE_DRAIN_MS   100 /* let the console flush before deep sleep    */
#define TEST_FIXED_PAYLOAD 0   /* PHY-crack scaffold, DISABLED. Set to 1 to bypass the simulator and transmit a fixed known 16-byte ramp (see app_exec) — useful for sniffing/decoding the raw LoRa PHY. */
#define RESTART_MS         30000

/*
 * A simulator is a test instrument, so it listens all the time: a command aimed at one of its
 * sensors is acted on when it is sent, not six hours later. Nothing is advertised -- a DOWN frame
 * is transmitted before it is held, so an always-listening node needs no invitation.
 *
 * SIMULATE_RECEIVE_ALWAYS=0 (see the Makefile) makes a board imitate a real sleeping sensor
 * instead, windows and advertisements and all, which is the only way to exercise that path on the
 * bench. When CONFIG becomes settable over the air this stops being a build-time choice.
 */
#ifndef SIMULATE_RECEIVE_ALWAYS
#define SIMULATE_RECEIVE_ALWAYS 1
#endif

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

#define PIN_DEVICE_UART_TX  PIN_E22_RXD
#define PIN_DEVICE_UART_RX  PIN_E22_TXD
#define PIN_DEVICE_LORA_AUX PIN_E22_AUX
#define PIN_DEVICE_LORA_M0  PIN_E22_M0
#define PIN_DEVICE_LORA_M1  PIN_E22_M1

#include "d_platform_esp32.h"
#include "d_common.h"
#include "d_hardware_gpio.h"
#include "d_hardware_uart.h"
#include "d_interface_e22900t22.h"
#include "d_module_datastore_esp32.h"

static const lora_config_t lora_cfg = {
    .e22_address = IOTDATA_CONFIG_LORA_ADDRESS,
    .e22_network = IOTDATA_CONFIG_LORA_NETWORK,
    .channel = IOTDATA_CONFIG_LORA_CHANNEL,
    .transmit_power = 22,  // dBm
    .air_data_rate = 2400, // bps
    .packet_size = 240,
    .listen_before_transmit = true,
    .crypt = 0x0000,
    .rssi_packet = true,
    .rssi_channel = false,
};

// -----------------------------------------------------------------------------------------------------------------------------------------
// iotdata
// -----------------------------------------------------------------------------------------------------------------------------------------

/*
 * Strip everything except the encoder for minimal ESP32 build:
 *   - NO_JSON:    no cJSON dependency
 *   - NO_DUMP:    no dump output
 *   - NO_PRINT:   no print output
 *   - NO_FLOATING: iotdata_float_t = int32_t (value * 100)
 */
#define IOTDATA_NO_JSON
#define IOTDATA_NO_DUMP
#define IOTDATA_NO_PRINT
#define IOTDATA_NO_FLOATING
#include "iotdata.h"
#include "iotdata.c"
#include "iotdata_node.h"

#include "iotdata_variant.h"

#include "iotdata_node_utils.h"
#include "iotdata_node_partial.h"
#include "iotdata_node_version.h"
// #include "iotdata_node_variant.h"
#include "iotdata_node_status.h"
// #include "iotdata_node_config.h"
#include "iotdata_node_control.h"
#define IOTDATA_DIAGNOSTICS       IOTDATA_CONFIG_BLACKBOX
#define IOTDATA_DIAGNOSTICS_FLUSH BLACKBOX_FLUSH_MANUAL /* a sleeping node flushes before it sleeps */
#define IOTDATA_BLACKBOX_IMPLEMENTATION
static void _node_diagnostics_emit(const char *const line) {
    ESP_LOGI("app", "%s", line); // XXX
}
#include "iotdata_node_diagnostics.h"
// #include "iotdata_node_content.h"
#define IOTDATA_STATE_BLOCKS_MAX (IOTDATA_CONFIG_SIMULATOR_NUM_SENSORS + 4)
#include "iotdata_node_state.h"
#include "iotdata_node_platform.h"

#include "iotdata_variant_simulator.h"
#include "iotdata_variant_simulator.c"

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

static const char *__tag_app = "app";

static uint32_t tx_count = 0, tx_errors = 0;

// -----------------------------------------------------------------------------------------------------------------------------------------
// Node personality, one per simulated sensor
//
// A simulator is a fleet in one box, so each virtual sensor keeps its own receive window and they
// drift apart rather than all waking together -- which is what a real fleet does, and the thing
// worth simulating.
//
// One difference from the real sensor: it appends RECEIVE to the telemetry frame it was already
// sending (two bytes), whereas here the frames are built inside the simulator library, so the
// advertisement goes out as a frame of its own immediately afterwards. Same moment, same effect on
// whoever is holding a command -- just an extra frame of airtime that a real node would not spend.
// -----------------------------------------------------------------------------------------------------------------------------------------

static iotsim_t g_sim;
static idep_node_t s_nodes[IOTDATA_CONFIG_SIMULATOR_NUM_SENSORS];

static datastore_t s_datastore;
static iotdata_node_state_t s_state;

/*
 * A block per virtual station, TAGGED BY STATION rather than by array index.
 *
 * The station ids come from this board's MAC (see app_init), so an index-derived tag would restore
 * one board's sequence onto a different board's station the moment the same image is flashed
 * elsewhere. Keyed by station, a foreign record simply finds no home and that sensor starts clean.
 * Stations are 12-bit, so this is unique and stable per station.
 */
#define SIM_STATE_TAG(station) (0x53490000UL | (uint32_t)(station)) /* "SI" + station */

static void sim_node_status(const uint16_t station, iotdata_node_status_t *const out) {
    out->uptime_s = (uint32_t)(hw_time_ms() / 1000);
    out->reason = IOTDATA_NODE_REASON_UNKNOWN;
    out->has_heap = true;
    out->heap_free = (uint32_t)esp_get_free_heap_size();
    out->heap_min = (uint32_t)esp_get_minimum_free_heap_size();
    for (int i = 0; i < (int)(sizeof(s_nodes) / sizeof(s_nodes[0])); i++)
        if (idep_station(&s_nodes[i]) == station) {
            const iotsim_sensor_t *const s = iotsim_sensor(&g_sim, i);
            if (s != NULL) {
                out->has_supply = true;
                out->supply_mv = (uint16_t)(s->battery * 30u); /* % -> a plausible mV */
            }
            break;
        }
}

static bool sim_node_tx(const uint8_t *const packet, const size_t len) {
    if (lora_write_complete(packet, len, /*wait_complete=*/true) == ESP_OK) {
        tx_count++;
        return true;
    } else {
        tx_errors++;
        return false;
    }
}

static iotdata_version_caps_t s_caps;

static const idep_config_t s_conf = {
    .caps = &s_caps,
    .status = sim_node_status,
    .tx = sim_node_tx,
    .control = IOTDATA_DIAGNOSTICS_CONTROL,
    .control_keys = iotdata_diagnostics_control_keys,
    .control_keys_count = IOTDATA_DIAGNOSTICS_CONTROL_KEYS_COUNT,
    .diag = IOTDATA_DIAGNOSTICS_PULL,
    .receive_always = (SIMULATE_RECEIVE_ALWAYS != 0),
    .receive_every_ms = IDEP_RECEIVE_EVERY_MS,
    .receive_window_ms = IDEP_RECEIVE_WINDOW_MS,
    .packet_max = LORA_PACKET_SIZE_MAX, /* what OUR radio carries; the framework sizes for the protocol */
};

// -----------------------------------------------------------------------------------------------------------------------------------------

static void receive_packets(__attribute__((unused)) iotsim_t *const sim) {
    const uint32_t now = hw_time_ms();

    bool any_open = false;
    for (int i = 0; i < (int)(sizeof(s_nodes) / sizeof(s_nodes[0])) && !any_open; i++)
        any_open = idep_window_active(&s_conf, &s_nodes[i], now);
    if (!any_open)
        return;

    uint8_t buf[IOTDATA_MAX_PACKET_SIZE];
    int len = 0, rssi_dbm = 0;
    /* 0ms first-byte timeout: this is a poll from the main loop, not a blocking receive. */
    while (lora_read(buf, sizeof(buf), &len, &rssi_dbm, 0) == ESP_OK && len > 0) {
        for (int i = 0; i < (int)(sizeof(s_nodes) / sizeof(s_nodes[0])); i++)
            if (idep_window_active(&s_conf, &s_nodes[i], hw_time_ms())) {
                bool reboot = false;
                if (idep_on_frame(&s_conf, &s_nodes[i], buf, (size_t)len, &reboot))
                    ESP_LOGI(__tag_app, "node: stn=%" PRIu16 " acted on a downstream command", idep_station(&s_nodes[i]));
                if (reboot) {
                    ESP_LOGW(__tag_app, "node: stn=%" PRIu16 " REBOOT commanded -- restarting", idep_station(&s_nodes[i]));
                    iotdata_diagnostics_event(IOTDATA_BB_LC_STOP, 0);
                    hw_delay_ms_yieldable(CONSOLE_DRAIN_MS);
                    esp_restart();
                }
            }
        len = 0;
    }

    for (int i = 0; i < (int)(sizeof(s_nodes) / sizeof(s_nodes[0])); i++)
        if (s_nodes[i].window_open && !idep_window_active(&s_conf, &s_nodes[i], hw_time_ms())) {
            idep_window_end(&s_nodes[i]);
            ESP_LOGI(__tag_app, "node: stn=%" PRIu16 " receive window closed", idep_station(&s_nodes[i]));
        }
}

// -----------------------------------------------------------------------------------------------------------------------------------------

static void transmit_packet(const iotsim_packet_t *pkt) {
    static char hex[512];
    hex[0] = '\0';
    for (size_t i = 0, o = 0; i < pkt->len && o < (sizeof(hex) - 1); i++)
        o += (size_t)snprintf(&hex[o], (sizeof(hex) - o) - 1, "%02" PRIX8, pkt->buf[i]);
    ESP_LOGI(__tag_app, "device: e22 tx #%06" PRIu32 ": stn=%-4" PRIu16 " %-18s seq=%06" PRIu16 " len=%-2" PRIu16 " hex=%s", tx_count, pkt->station_id, iotdata_vsuite_name(pkt->variant), pkt->sequence, (uint16_t)pkt->len, hex);
    if (lora_write_complete(pkt->buf, pkt->len, /*wait_complete=*/true) == ESP_OK)
        tx_count++;
    else {
        tx_errors++;
        ESP_LOGE(__tag_app, "device: e22 tx lora_write_complete failed (errors=%" PRIu32 ")", tx_errors);
    }
}

static void transmit_packets(iotsim_t *const sim) {
    iotsim_packet_t pkt;
    while (iotsim_poll(sim, hw_time_ms(), &pkt)) {
        transmit_packet(&pkt);
        hw_delay_ms_yieldable(TRANSMIT_DELAY_MS);
        const int idx = pkt.sensor_index;
        if (idx >= 0 && idx < (int)(sizeof(s_nodes) / sizeof(s_nodes[0])))
            idep_sequence_used(&s_nodes[idx]); /* in lockstep with the engine's own advance */
        if (idx >= 0 && idx < (int)(sizeof(s_nodes) / sizeof(s_nodes[0])) && idep_window_pending(&s_nodes[idx])) {
            s_nodes[idx].sequence = (uint16_t)(pkt.sequence + 1u);
            if (idep_receive_announce(&s_conf, &s_nodes[idx])) {
                idep_window_begin(&s_conf, &s_nodes[idx], hw_time_ms());
                ESP_LOGI(__tag_app, "node: stn=%" PRIu16 " receive window open for %ums", idep_station(&s_nodes[idx]), (unsigned)IDEP_RECEIVE_WINDOW_MS);
            }
            hw_delay_ms_yieldable(TRANSMIT_DELAY_MS);
        }
    }
}

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

bool app_init(void) {
    const esp_reset_reason_t reset_reason = esp_reset_reason();
    const bool restarted = (reset_reason != ESP_RST_DEEPSLEEP);

    ESP_LOGI(__tag_app, "iotdata multi-sensor simulator transmitter");
    ESP_LOGI(__tag_app, "boot: reset_reason=%d %s", (int)reset_reason, reset_reason_str(reset_reason));

    iotdata_diagnostics_emit_set(_node_diagnostics_emit);
    if (!iotdata_diagnostics_begin((uint8_t)reset_reason, restarted))
        ESP_LOGW(__tag_app, "diagnostics: the recorder did not start");

    iotdata_version_caps_init(&s_caps);

    char vbuf[IOTDATA_VERSION_STR_MAX + 1];
    ESP_LOGI(__tag_app, "version: %s", iotdata_version_str(vbuf, sizeof(vbuf), &s_caps));
    if (!iotdata_version_stamp_is_real())
        ESP_LOGW(__tag_app, "version: build stamp is unset -- this binary cannot say when it was built");

    /* --- Hardware init --- */
    esp_err_t lerr;
    if ((lerr = lora_setup(&lora_cfg)) != ESP_OK) {
        ESP_LOGE(__tag_app, "device: e22 setup failed: %s", esp_err_to_name(lerr));
        iotdata_diagnostics_event(IOTDATA_BB_LC_ERROR, 2);
        return false;
    }
    ESP_LOGI(__tag_app, "device: e22 configured");
    if ((lerr = lora_start()) != ESP_OK) {
        ESP_LOGE(__tag_app, "device: e22 start failed: %s", esp_err_to_name(lerr));
        iotdata_diagnostics_event(IOTDATA_BB_LC_ERROR, 3);
        return false;
    }
    ESP_LOGI(__tag_app, "device: e22 configured, transfer mode active");
    iotdata_diagnostics_event(IOTDATA_BB_LC_START, 0);

    /* --- Simulator init --- Identity comes from the factory MAC so each board is
       unique AND stable across reboots: a per-board station_base (disjoint ID band)
       and a fixed seed (so each board's station->variant map never changes). Flash
       the same firmware to every board; they self-separate on air. */
    uint8_t mac[6] = { 0 };
    (void)esp_efuse_mac_get_default(mac);
    const uint32_t mac32 = ((uint32_t)mac[2] << 24) | ((uint32_t)mac[3] << 16) | ((uint32_t)mac[4] << 8) | mac[5];
    const uint32_t seed = mac32 ? mac32 : 0xDEADBEEFU;
    const uint16_t nbands = (uint16_t)(IOTDATA_STATION_ASSIGNABLE_MAX / IOTDATA_CONFIG_SIMULATOR_NUM_SENSORS); /* 4094/8 = 511 */
    const uint16_t station_base = (uint16_t)((mac32 % nbands) * (uint32_t)IOTDATA_CONFIG_SIMULATOR_NUM_SENSORS);
    iotsim_init(&g_sim, seed, hw_time_ms(), station_base);
    ESP_LOGI(__tag_app, "board: mac=%02X:%02X:%02X:%02X:%02X:%02X seed=%08" PRIX32 " stations=%" PRIu16 "-%" PRIu16, (unsigned)mac[0], (unsigned)mac[1], (unsigned)mac[2], (unsigned)mac[3], (unsigned)mac[4], (unsigned)mac[5], seed,
             (uint16_t)(station_base + 1), (uint16_t)(station_base + IOTDATA_CONFIG_SIMULATOR_NUM_SENSORS));
    ESP_LOGI(__tag_app, "simulator: sensors=%d, types/board=%d, tx_interval=%u-%us", IOTDATA_CONFIG_SIMULATOR_NUM_SENSORS, IOTDATA_CONFIG_SIMULATOR_VARIANT_TYPES, (unsigned)(IOTDATA_CONFIG_SIMULATOR_TX_MIN_MS / 1000),
             (unsigned)(IOTDATA_CONFIG_SIMULATOR_TX_MAX_MS / 1000));
    if (datastore_open(&s_datastore, "iotdata"))
        iotdata_state_init(&s_state, &s_datastore, "state");
    else
        ESP_LOGW(__tag_app, "state: persistence disabled (no datastore)");

    /* Each node registers its own sequence as it comes up; the load afterwards fills them all in
       one pass, and nothing may register after it. */
    for (int i = 0; i < (int)(sizeof(s_nodes) / sizeof(s_nodes[0])); i++) {
        const iotsim_sensor_t *s = iotsim_sensor(&g_sim, i);
        idep_node_init(&s_nodes[i], s->station_id, &s_state, SIM_STATE_TAG(s->station_id));
        s_nodes[i].elapsed_ms = (uint32_t)((uint64_t)IDEP_RECEIVE_EVERY_MS * (uint32_t)i / IOTDATA_CONFIG_SIMULATOR_NUM_SENSORS);
        ESP_LOGI(__tag_app, "  [%2d] %-18s stn=%-4" PRIu16 " bat=%" PRIu8 "%%", i, iotdata_vsuite_name(s->variant), s->station_id, s->battery);
    }

    /* The node is the source of truth; the engine is seeded from it and then advances in lockstep
       (iotsim_poll bumps its own, transmit_packets calls idep_sequence_used on the node). The
       engine keeping a counter at all is the remaining wart -- properly it would be handed the
       sequence per packet, which means changing iotsim's encode signature. */
    const bool restored = iotdata_state_load(&s_state);
    for (int i = 0; i < (int)(sizeof(s_nodes) / sizeof(s_nodes[0])); i++)
        iotsim_sensor_sequence_set(&g_sim, i, idep_sequence(&s_nodes[i]));
    ESP_LOGI(__tag_app, "state: %u block(s), %s", (unsigned)s_state.count, restored ? "restored" : "defaulted");
    if (s_conf.receive_always)
        ESP_LOGI(__tag_app, "node: receiver always on (no advertisement needed), per sensor");
    else
        ESP_LOGI(__tag_app, "node: receive window %us every %uh, per sensor", (unsigned)(IDEP_RECEIVE_WINDOW_MS / 1000), (unsigned)(IDEP_RECEIVE_EVERY_MS / 3600000u));
    return true;
}

// -----------------------------------------------------------------------------------------------------------------------------------------

bool app_exec(void) {
    const uint32_t start_ms = hw_time_ms();
    uint32_t tx_count_last = 0, window_last_ms = hw_time_ms();
    do {
        const uint32_t delta = hw_time_ms() - window_last_ms;
        window_last_ms = hw_time_ms();
        for (int i = 0; i < (int)(sizeof(s_nodes) / sizeof(s_nodes[0])); i++)
            (void)idep_window_advance(&s_conf, &s_nodes[i], delta);

        transmit_packets(&g_sim);
        receive_packets(&g_sim);
        (void)iotdata_diagnostics_pump(); /* drains a DUMP a chunk per pass, so the loop keeps time */
        (void)iotdata_state_tick(&s_state, hw_time_ms());

        if (tx_count >= tx_count_last + STATUS_EVERY_N_TX) {
            tx_count_last = tx_count;
            ESP_LOGI(__tag_app, "status: tx=%" PRIu32 " errors=%" PRIu32 " uptime=%" PRIu32 "s", tx_count, tx_errors, (hw_time_ms() - start_ms) / 1000);
        }
        hw_delay_ms_yieldable(POLL_INTERVAL_MS);
    } while (true);
    return true;
}

// -----------------------------------------------------------------------------------------------------------------------------------------

void app_fail(void) {
    ESP_LOGE(__tag_app, "failed");
    iotdata_diagnostics_event(IOTDATA_BB_LC_STOP, 0);
    hw_delay_ms_yieldable(RESTART_MS);
    esp_restart();
}

// -----------------------------------------------------------------------------------------------------------------------------------------

void app_main(void) {

    setbuf(stdout, NULL);

    const esp_err_t wdt_err = esp_task_wdt_add(NULL);
    if (wdt_err != ESP_OK)
        ESP_LOGE(__tag_app, "task watchdog: subscribe failed: %s", esp_err_to_name(wdt_err));
    else
        ESP_LOGI(__tag_app, "task watchdog: subscribed (timeout=%ds)", CONFIG_ESP_TASK_WDT_TIMEOUT_S);

    if (!app_init() || !app_exec())
        app_fail();
}

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------
